---
name: Moderne ingest

on:
  workflow_dispatch:
  push:
    branches: [ 1.5.x ]
  schedule:
    - cron: "0 18 * * *"

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ingest
        uses: docker://moderne/ingest:java11-latest
        env:
          MODERNE_API_ACCESS_TOKEN: ${{ secrets.MODERNE_API_ACCESS_TOKEN }}
